package com.anjan.LeaveManagement.model;
// default package
// Generated Feb 22, 2018 11:26:36 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees", catalog = "db_leave")
public class Employees implements java.io.Serializable {

	private Integer id;
	private String name;
	private int deptId;
	private Set<Leaves> leaveses = new HashSet<Leaves>(0);
	private Set<Department> departments = new HashSet<Department>(0);

	public Employees() {
	}

	public Employees(String name, int deptId) {
		this.name = name;
		this.deptId = deptId;
	}

	public Employees(String name, int deptId, Set<Leaves> leaveses, Set<Department> departments) {
		this.name = name;
		this.deptId = deptId;
		this.leaveses = leaveses;
		this.departments = departments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "dept_id", nullable = false)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Leaves> getLeaveses() {
		return this.leaveses;
	}

	public void setLeaveses(Set<Leaves> leaveses) {
		this.leaveses = leaveses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

}
